In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[-1]

10

In [8]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [10]:
slice = arr[0:6]

In [11]:
slice

array([0, 1, 2, 3, 4, 5])

In [13]:
slice[:] = 99

In [14]:
slice

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [17]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr.shape

(3, 3)

In [20]:
arr[1][1]

25

In [21]:
arr[-1]

array([35, 40, 45])

In [22]:
arr[-1,-1]

45

In [24]:
arr[:2, 1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr = np.arange(1,11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
bool_arr = arr > 4

In [29]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])