In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mymatrix = np.array(mylist)

In [10]:
mymatrix.shape

(3, 3)

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.random.rand(4)

array([0.4666324 , 0.69531793, 0.28932205, 0.5104745 ])

In [20]:
np.random.randn(3)

array([-2.21531351, -2.55319738,  0.68479573])

In [21]:
np.random.randint(0,800)

418

In [22]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,50,10)

In [26]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [27]:
arr.shape

(25,)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
len(arr)

25

In [30]:
ranarr.max()

39

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmax()

7

In [35]:
ranarr.argmin()

9

In [34]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [36]:
ranarr.dtype

dtype('int32')