In [4]:
!pip install torch

In [5]:
import torch

In [6]:
torch.__version__

'2.0.1'

In [7]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
print(arr)

[1 2 3 4 5]


In [10]:
arr.dtype

dtype('int32')

In [11]:
type(arr)

numpy.ndarray

In [13]:
x = torch.from_numpy(arr)

In [14]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [15]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [16]:
arr = np.arange(0.0,12.0)

In [17]:
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [18]:
arr2d = arr.reshape(4,3)

In [19]:
x2 = torch.from_numpy(arr2d)

In [20]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [21]:
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [22]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [23]:
arr[0] = 99

In [24]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [25]:
arr = np.arange(0,10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
tensor = torch.tensor(arr)

In [28]:
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [29]:
arr = np.array([1,2,3])

In [30]:
torch.tensor(arr)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
torch.Tensor(arr)

tensor([1., 2., 3.])

In [32]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [33]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [35]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [36]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [37]:
torch.rand(4,3)

tensor([[0.8186, 0.5924, 0.0988],
        [0.5648, 0.8083, 0.8584],
        [0.1061, 0.0659, 0.0329],
        [0.8852, 0.5723, 0.1139]])

In [38]:
torch.randn(4,3)

tensor([[ 1.7584, -1.5228, -0.1246],
        [ 0.0967, -0.6536, -0.6243],
        [ 0.4914,  1.4650, -0.9934],
        [-0.8814, -0.0532, -1.2180]])

In [39]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[7, 3, 7, 7, 4],
        [5, 3, 6, 5, 0],
        [7, 4, 4, 0, 0],
        [5, 7, 5, 6, 6],
        [5, 7, 5, 6, 6]])

In [40]:
x = torch.zeros(2,5)

In [41]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [42]:
torch.rand_like(x)

tensor([[0.6708, 0.0252, 0.4493, 0.8172, 0.0112],
        [0.6200, 0.3232, 0.7880, 0.9639, 0.3986]])