In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
x[1,1]

tensor(3)

In [5]:
x[:,1]

tensor([1, 3, 5])

In [6]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [7]:
x = torch.arange(10)

In [8]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = torch.arange(10)

In [14]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x.shape

torch.Size([10])

In [16]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
z = x.view(2,5)

In [19]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
x[0] = 9999

In [21]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [22]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [23]:
x = torch.arange(10)

In [24]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x.shape

torch.Size([10])

In [26]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
a = torch.tensor([1.,2.,3.])

In [28]:
b = torch.tensor([4.,5.,6.])

In [29]:
a

tensor([1., 2., 3.])

In [30]:
b

tensor([4., 5., 6.])

In [31]:
a + b

tensor([5., 7., 9.])

In [32]:
a.mul(b)

tensor([ 4., 10., 18.])

In [33]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [34]:
a

tensor([ 4., 10., 18.])

In [35]:
a = torch.tensor([1.,2.,3.])

In [36]:
a

tensor([1., 2., 3.])

In [37]:
b

tensor([4., 5., 6.])

In [38]:
a * b

tensor([ 4., 10., 18.])

In [39]:
a.dot(b)

tensor(32.)

In [40]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [41]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [42]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [43]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [44]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [45]:
 a @ b

tensor([[56, 62],
        [80, 89]])

In [46]:
x = torch.tensor([2.,3.,4.,5.])

In [47]:
x.norm()

tensor(7.3485)

In [49]:
x.numel()

4